### ISSUE TITLE
Deprecated selector in `atom-dione\styles\atom-tracer.atom-text-editor.less`

### ISSUE THREAD

**Issue by estefany19** [gimenete/atom-dione#1]
In `atom-dione\styles\atom-tracer.atom-text-editor.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor .gutter .line-number.traced,
atom-text-editor::shadow .gutter .line-number.traced` => `atom-text-editor .gutter .line-number.traced,
atom-text-editor.editor .gutter .line-number.traced`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by gimenete** [comment]
@estefany19 thank you so much for reporting this. However this is a very old experiment I did and personally I'm no longer using Atom, so I'm going to mark the project as no longer maintained.

Feel free to fork it! That would be great.
